"""Add name column to user_registry table

Revision ID: 1463886147cc
Revises: 
Create Date: 2025-09-21 17:50:08.120990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1463886147cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('path', sa.String(), nullable=True))
    op.add_column('user_registry', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_registry', 'name')
    op.drop_column('knowledge_bases', 'path')
    # ### end Alembic commands ###
